export default {
    baseUrl: 'api',
    login:'/login',//登录
    keyword_list:'/keyword_list',//关键词列表
    add_keyword:"/add_keyword",//添加爬虫关键词
    del_keyword:'/del_keyword',//删除爬虫关键词
    site_list:"/site_list",//爬虫网站列表
    news_list:'/news_list',//爬虫新闻列表
    comment_list:'/comment_list',//评论(舆情)列表
    config:'/config',//配置参数详情
    adminuser_list:'/adminuser_list',//账号列表
    add_adminuser:"/add_adminuser",//账号--添加账号
    limits:'/limits',//账号--权限列表
    update_adminuser:'/update_adminuser',//账号--修改账号
    adminuser_del:'/adminuser_del',//账号--删除账号
    select_news:'/select_news',//筛选新闻
    select_comment:'/select_comment',//筛选评论
    screen_newslist:'/screen_newslist',//爬虫新闻列表（筛选后）
    screen_commentlist:'/screen_commentlist',//评论(舆情)列表(筛选后)
    add_pubsentimentkeyword:'/add_pubsentimentkeyword',//添加舆情关键词
    pubsentiment_keywordlist:"/pubsentiment_keywordlist",//舆情关键词
    del_pubsentimentkeyword:'/del_pubsentimentkeyword',//删除舆情关键词
    hotwords_logs:'/hotwords_logs',//热词统计
    video_list:'/video_list',//视频列表(未筛选)
    screen_videolist:'/screen_videolist',//视频列表(筛选后)
    select_video:"/select_video",//选中视频
    add_hotlink:'/add_hotlink',//添加热度链接
    newstopublicsentiment:'/newstopublicsentiment',//新闻转到舆情
    publicsentimenttonews:"/publicsentimenttonews",//舆情转到新闻
    news_edit:'/news_edit',//新闻修改
    news_del:'/news_del',//新闻删除
    pubsentiment_edit:'/pubsentiment_edit',//舆情修改
    pubsentiment_del:'/pubsentiment_del',//舆情删除
    video_edit:"/video_edit",//视频修改
    video_del:'/video_del',//视频删除
    heat_entry:'/heat_entry',//热度词条
    screen_newsedit:'/screen_newsedit',//新闻修改(筛选后)
    screen_pubsentimenteditL:'/screen_pubsentimentedit',//舆情修改(筛选后)
    screen_videoedit:'/screen_videoedit',//视频修改(筛选后)
    export_list:'/export_list',//导出新闻
    screen_newsdel:'/screen_newsdel',//新闻删除(筛选后)
    screen_pubsentimentdel:'/screen_pubsentimentdel',//舆情删除(筛选后)
    screen_videodel:'/screen_videodel',//视频删除(筛选后)
    exporthotwords_list:'/exporthotwords_list',//导出热词
    hotwords_list:'/hotwords_list',//关键词设定列表
    del_hotwords:"/del_hotwords",//删除关键词设定
    user_release:'/user_release',//发布新闻/舆情/视频
    check_hotlink:"/check_hotlink",//添加热度链接(根据链接获取内容)
    info_list:'/info_list',//温州教育列表
    add_info:'/add_info',//添加温州教育
    update_info:'/update_info',//修改温州教育
    del_info:'/del_info',//删除温州教育
    admingroups_list:'/admingroups_list',//账号组别列表
    update_admingroup:'/update_admingroup',//修改账号组别
    update_hotwords:'/update_hotwords',//修改关键词设定
    manual_reptile:'/manual_reptile',//手动一键采集
    list_hotwordskeyword:'/list_hotwordskeyword',//热词列表(手动)
    add_hotwordskeyword:'/add_hotwordskeyword',//添加热词(手动)
    del_hotwordskeyword:'/del_hotwordskeyword',//删除热词(手动)
}
